/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Date = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const DailySummary = IDL.Record({
  'totalCarbs' : IDL.Nat,
  'totalFat' : IDL.Nat,
  'totalCalories' : IDL.Nat,
  'totalSteps' : IDL.Nat,
  'totalProtein' : IDL.Nat,
  'latestWeight' : IDL.Opt(IDL.Float64),
  'totalWaterMl' : IDL.Nat,
});
export const ExerciseType = IDL.Variant({
  'strength' : IDL.Null,
  'cardio' : IDL.Null,
});
export const MuscleGroup = IDL.Variant({
  'shoulders' : IDL.Null,
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
  'fullBody' : IDL.Null,
  'cardio' : IDL.Null,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'exerciseType' : ExerciseType,
  'muscleGroup' : MuscleGroup,
});
export const FoodEntry = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'protein' : IDL.Nat,
});
export const ExerciseSet = IDL.Record({
  'weight' : IDL.Nat,
  'duration' : IDL.Nat,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'exerciseName' : IDL.Text,
});
export const WorkoutLog = IDL.Record({
  'date' : Date,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(ExerciseSet),
});
export const BodyMetric = IDL.Record({
  'weightLbs' : IDL.Float64,
  'date' : Date,
  'bodyFatPercentage' : IDL.Float64,
});
export const StepsLog = IDL.Record({ 'date' : Date, 'steps' : IDL.Nat });
export const WaterIntake = IDL.Record({ 'date' : Date, 'amountMl' : IDL.Nat });
export const DailyGoals = IDL.Record({
  'weightGoalLbs' : IDL.Float64,
  'calorieGoal' : IDL.Nat,
  'stepGoal' : IDL.Nat,
  'waterGoalMl' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailySummary' : IDL.Func([Date], [DailySummary], ['query']),
  'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getNutritionEntries' : IDL.Func([Date], [IDL.Vec(FoodEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkouts' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logBodyMetric' : IDL.Func([BodyMetric], [], []),
  'logNutritionEntry' : IDL.Func([Date, FoodEntry], [], []),
  'logSteps' : IDL.Func([StepsLog], [], []),
  'logWaterIntake' : IDL.Func([WaterIntake], [], []),
  'logWorkout' : IDL.Func([WorkoutLog], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyGoals' : IDL.Func([DailyGoals], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Date = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const DailySummary = IDL.Record({
    'totalCarbs' : IDL.Nat,
    'totalFat' : IDL.Nat,
    'totalCalories' : IDL.Nat,
    'totalSteps' : IDL.Nat,
    'totalProtein' : IDL.Nat,
    'latestWeight' : IDL.Opt(IDL.Float64),
    'totalWaterMl' : IDL.Nat,
  });
  const ExerciseType = IDL.Variant({
    'strength' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const MuscleGroup = IDL.Variant({
    'shoulders' : IDL.Null,
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
    'fullBody' : IDL.Null,
    'cardio' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'exerciseType' : ExerciseType,
    'muscleGroup' : MuscleGroup,
  });
  const FoodEntry = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'protein' : IDL.Nat,
  });
  const ExerciseSet = IDL.Record({
    'weight' : IDL.Nat,
    'duration' : IDL.Nat,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'exerciseName' : IDL.Text,
  });
  const WorkoutLog = IDL.Record({
    'date' : Date,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(ExerciseSet),
  });
  const BodyMetric = IDL.Record({
    'weightLbs' : IDL.Float64,
    'date' : Date,
    'bodyFatPercentage' : IDL.Float64,
  });
  const StepsLog = IDL.Record({ 'date' : Date, 'steps' : IDL.Nat });
  const WaterIntake = IDL.Record({ 'date' : Date, 'amountMl' : IDL.Nat });
  const DailyGoals = IDL.Record({
    'weightGoalLbs' : IDL.Float64,
    'calorieGoal' : IDL.Nat,
    'stepGoal' : IDL.Nat,
    'waterGoalMl' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailySummary' : IDL.Func([Date], [DailySummary], ['query']),
    'getExerciseLibrary' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getNutritionEntries' : IDL.Func([Date], [IDL.Vec(FoodEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkouts' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logBodyMetric' : IDL.Func([BodyMetric], [], []),
    'logNutritionEntry' : IDL.Func([Date, FoodEntry], [], []),
    'logSteps' : IDL.Func([StepsLog], [], []),
    'logWaterIntake' : IDL.Func([WaterIntake], [], []),
    'logWorkout' : IDL.Func([WorkoutLog], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyGoals' : IDL.Func([DailyGoals], [], []),
  });
};

export const init = ({ IDL }) => { return []; };