/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyMetric {
  'weightLbs' : number,
  'date' : Date,
  'bodyFatPercentage' : number,
}
export interface DailyGoals {
  'weightGoalLbs' : number,
  'calorieGoal' : bigint,
  'stepGoal' : bigint,
  'waterGoalMl' : bigint,
}
export interface DailySummary {
  'totalCarbs' : bigint,
  'totalFat' : bigint,
  'totalCalories' : bigint,
  'totalSteps' : bigint,
  'totalProtein' : bigint,
  'latestWeight' : [] | [number],
  'totalWaterMl' : bigint,
}
export interface Date { 'day' : bigint, 'month' : bigint, 'year' : bigint }
export interface Exercise {
  'name' : string,
  'exerciseType' : ExerciseType,
  'muscleGroup' : MuscleGroup,
}
export interface ExerciseSet {
  'weight' : bigint,
  'duration' : bigint,
  'reps' : bigint,
  'sets' : bigint,
  'exerciseName' : string,
}
export type ExerciseType = { 'strength' : null } |
  { 'cardio' : null };
export interface FoodEntry {
  'fat' : bigint,
  'carbs' : bigint,
  'calories' : bigint,
  'name' : string,
  'protein' : bigint,
}
export type MuscleGroup = { 'shoulders' : null } |
  { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null } |
  { 'fullBody' : null } |
  { 'cardio' : null };
export interface StepsLog { 'date' : Date, 'steps' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WaterIntake { 'date' : Date, 'amountMl' : bigint }
export interface WorkoutLog {
  'date' : Date,
  'name' : string,
  'exercises' : Array<ExerciseSet>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailySummary' : ActorMethod<[Date], DailySummary>,
  'getExerciseLibrary' : ActorMethod<[], Array<Exercise>>,
  'getNutritionEntries' : ActorMethod<[Date], Array<FoodEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkouts' : ActorMethod<[], Array<WorkoutLog>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logBodyMetric' : ActorMethod<[BodyMetric], undefined>,
  'logNutritionEntry' : ActorMethod<[Date, FoodEntry], undefined>,
  'logSteps' : ActorMethod<[StepsLog], undefined>,
  'logWaterIntake' : ActorMethod<[WaterIntake], undefined>,
  'logWorkout' : ActorMethod<[WorkoutLog], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDailyGoals' : ActorMethod<[DailyGoals], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];